image: node:latest

stages:
  - deploy

variables:
  GIT_SUBMODULE_STRATEGY: recursive

deploy:
  stage: deploy
  script:
    - cd bible-frontend
    - npm install
    - npm run build
    - npm run deploy
  only:
    - master
