# The Docker image that will be used to build your app
image: node:latest
# Functions that should be executed before the build script is run
before_script:
  - cd bible-frontend
  - npm install
  - npm run build
  - npm run deploy
